// demos/vue/src/pages/User.vue
<script setup lang="ts">
import { useParams } from "@isorouter/vue";

// useParams() returns a ComputedRef<Record<string, string>>.
// Vue auto-unwraps it in the template, so params.id works without .value.
const params = useParams();
</script>

<template>
  <h1>User profile</h1>
  <p>
    ID: <strong>{{ params.id }}</strong>
  </p>
  <p><em>This component is lazy-loaded (code-split by Vite).</em></p>
</template>

// demos/react/src/pages/User.tsx
import { useParams } from "@isorouter/react";

export default function User() {
  // useParams() is typed as Record<string, string> by default;
  // pass a generic to narrow it: useParams<{ id: string }>()
  const { id } = useParams<{ id: string }>();

  return (
    <>
      <h1>User profile</h1>
      <p>
        ID: <strong>{id}</strong>
      </p>
      <p>
        <em>This component is lazy-loaded (code-split by Vite).</em>
      </p>
    </>
  );
}
