// packages/react/src/Router.tsx
import { useEffect, type ReactNode } from "react";

import { DepthContext, RouterContext } from "./context";
import type { AnyReactRouter } from "./types";
import { useRouterState } from "./hooks";

export interface RouterProps {
  router: AnyReactRouter;
  notFound?: ReactNode;
  error?: (err: unknown) => ReactNode;
  loading?: ReactNode;
}

export function Router({ router, notFound, error, loading }: RouterProps) {
  useEffect(() => {
    router.start();

    return () => router.stop();
  }, [router]);

  return (
    <RouterContext.Provider value={router}>
      <DepthContext.Provider value={0}>
        <RouterView notFound={notFound} error={error} loading={loading} />
      </DepthContext.Provider>
    </RouterContext.Provider>
  );
}

function RouterView({ notFound, error, loading }: Omit<RouterProps, "router">) {
  const state = useRouterState();

  if (state.status === "error" && error) return <>{error(state.error)}</>;

  if (state.status === "not-found" && notFound) return <>{notFound}</>;

  const Root = state.components[0];

  if (Root) return <Root />;

  return <>{loading ?? null}</>;
}

// packages/svelte/src/Router.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import { setOutletContext } from "./context";

  import type { Snippet } from "svelte";
  import type { AnySvelteRouter } from "./types";

  let {
    router,
    notFound,
    error,
    loading,
  }: {
    router: AnySvelteRouter;
    notFound?: Snippet;
    error?: Snippet<[unknown]>;
    loading?: Snippet;
  } = $props();

  setOutletContext({ depth: 0, router });

  onMount(() => {
    router.start();
    return () => router.stop();
  });

  const Root = $derived(router.current.components[0]);
  const status = $derived(router.current.status);
</script>

{#if status === "error" && error}
  {@render error(router.current.error)}
{:else if status === "not-found" && notFound}
  {@render notFound()}
{:else if Root}
  <Root />
{:else if loading}
  {@render loading()}
{/if}
