// packages/svelte/src/Link.svelte
<script lang="ts">
  import { getOutletContext } from "./context";

  import type { Snippet } from "svelte";

  let {
    href,
    class: className = "",
    activeClass = "active",
    exact = false,
    children,
    ...rest
  }: {
    href: string;
    class?: string;
    activeClass?: string;
    exact?: boolean;
    children?: Snippet;
    [key: string]: unknown;
  } = $props();

  const ctx = getOutletContext();
  const active = $derived(ctx?.router?.isActive(href, { exact }) ?? false);
</script>

<a
  {href}
  class={`${className} ${active ? activeClass : ""}`.trim()}
  aria-current={active ? "page" : undefined}
  {...rest}
>
  {@render children?.()}
</a>

// packages/react/src/Link.tsx
import { forwardRef, type AnchorHTMLAttributes } from "react";

import { useRouterInstance } from "./context";
import { useRouterState } from "./hooks";

export interface LinkProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
  href: string;
  activeClassName?: string;
  exact?: boolean;
}

export const Link = forwardRef<HTMLAnchorElement, LinkProps>(
  (
    {
      href,
      className = "",
      activeClassName = "active",
      exact = false,
      children,
      ...rest
    },
    ref,
  ) => {
    const router = useRouterInstance();

    useRouterState(); // re-render on navigation to update active state

    const active = router.isActive(href, { exact });
    const classes = `${className} ${active ? activeClassName : ""}`.trim();

    return (
      <a
        ref={ref}
        href={href}
        className={classes || undefined}
        aria-current={active ? "page" : undefined}
        {...rest}
      >
        {children}
      </a>
    );
  },
);

Link.displayName = "Link";
