// demos/svelte/src/pages/User.svelte
<script lang="ts">
  import { getRouter } from "@isorouter/svelte";

  // getRouter() returns the narrowed SvelteRouter because Register is augmented in router.ts.
  // router.current is a reactive getter — reading it here subscribes the template to commits.
  const router = getRouter();
</script>

<h1>User profile</h1>
<p>ID: <strong>{router.current.params.id}</strong></p>
<p><em>This component is lazy-loaded (code-split by Vite).</em></p>

// demos/vue/src/pages/User.vue
<script setup lang="ts">
import { useParams } from "@isorouter/vue";

// useParams() returns a ComputedRef<Record<string, string>>.
// Vue auto-unwraps it in the template, so params.id works without .value.
const params = useParams();
</script>

<template>
  <h1>User profile</h1>
  <p>
    ID: <strong>{{ params.id }}</strong>
  </p>
  <p><em>This component is lazy-loaded (code-split by Vite).</em></p>
</template>
